### ISSUE TITLE
no data available after upgrade to FRITZ!OS 07.26

### ISSUE THREAD

**Issue by filly82** [rodney42/fritznode#2]
``
      let con = await fritz.fritz({
         user: '<USER>',
         password: '<PWD>',
         host: "fritz.box"
      });
      console.log(con);
      let devices = await con.getDeviceList();
      console.log(devices);
``

``
INFO  : Login <USER>@fritz.box ... 
INFO  : Login <USER>@fritz.box ... done.
{
  sid: [ 'd3...............' ],
  getDeviceList: [AsyncFunction: getDeviceList],      
  getBandwithUsage: [AsyncFunction: getBandwithUsage],
  getOverview: [AsyncFunction: getOverview],
  getNAS: [AsyncFunction: getNAS]
}
``

no output of `console.log(devices);` at all. no error in the console

**Comment by rodney42** [comment]
Sorry for late reply. Reason for the failure: The latest fritz os versions require to use a pbkdf2 challenge response. This is implemented in version 0.0.3 now.
